server:
  port: "8080"
  
database:
  driver: "postgres"
  dsn: "user=postgres password=1234 dbname=postgres host=localhost port=5432 sslmode=disable"

logger:
  level: "info"

user:
  salt: "somerandomsalt"
  jwt_secret: "somerandomjwtsecret"